services:
  # Aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mtr-api-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./.env:/var/www/html/.env
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=db_matricula
      - DB_USERNAME=root
      - DB_PASSWORD=Dev2025
      - DB_SSL_MODE=DISABLED
    networks:
      - mtr-network

networks:
  mtr-network:
    driver: bridge 